package com.minijira.enums;

/**
 * ROLES AVAILABLE IN THE SYSTEM.
 * ADMIN    - FULL ACCESS: MANAGE USERS, PROJECTS, TASKS WITHIN THE ORGANIZATION
 * MANAGER  - MANAGE PROJECTS AND TASKS, ASSIGN MEMBERS; CANNOT MANAGE USERS
 * MEMBER   - VIEW AND UPDATE ONLY TASKS ASSIGNED TO THEM
 */
public enum Role {
    ADMIN,
    MANAGER,
    MEMBER
}
