-- ============================================================
-- V1__baseline.sql
-- BASELINE MIGRATION - MARKS THE STARTING POINT FOR ALL FUTURE SCHEMA CHANGES
-- ACTUAL TABLE CREATION STARTS FROM V2 ONWARDS ONCE ENTITIES ARE DEFINED
-- ============================================================

-- THIS FILE IS INTENTIONALLY MINIMAL - JUST ESTABLISHES THE FLYWAY BASELINE
-- SO SUBSEQUENT MIGRATIONS HAVE A CLEAN STARTING POINT TO BUILD ON TOP OF

SELECT 1; -- NO-OP STATEMENT SO FLYWAY HAS VALID SQL TO EXECUTE
